# Generated by Django 5.0.4 on 2024-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/user'),
            preserve_default=False,
        ),
    ]
