# Generated by Django 5.0.4 on 2024-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/user/default.jpg', upload_to='images/user'),
        ),
    ]
