# Generated by Django 5.0.4 on 2024-04-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
