# Generated by Django 5.0.4 on 2024-04-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
