# Generated by Django 5.0.4 on 2024-04-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
