# Generated by Django 5.0.4 on 2024-04-12 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_country_user_facebook_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^01[012]\\d{8}$')]),
        ),
    ]
