# Generated by Django 5.0.4 on 2024-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_owner'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tages',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
