# Generated by Django 5.0.4 on 2024-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_tages'),
        ('tags', '0002_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tages',
            field=models.ManyToManyField(related_name='tagProject', to='tags.tag'),
        ),
    ]
