# Generated by Django 5.0.4 on 2024-04-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_tages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
