# Generated by Django 5.0.4 on 2024-05-07 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_options_alter_importantproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target_money',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
