"""
Django settings for crowdfunding project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&^7f@18=mqn*3bkh04118n$tp*x$th7b%qslgng8bewaq_)_k6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "sslserver",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_cleanup.apps.CleanupConfig",
    "api.apps.ApiConfig",
    "rest_framework",
    "tags.apps.TagsConfig",
    "rating.apps.RatingConfig",
    "project_report.apps.ProjectReportConfig",
    "comment.apps.CommentConfig",
    "comment_report.apps.CommentReportConfig",
    "replay.apps.ReplayConfig",
    # Donation App
    "Donation.apps.DonationConfig",
    # Project Pics App
    "Project_Pics.apps.ProjectPicsConfig",
    # Reset Password
    "Reset_Password.apps.ResetPasswordConfig",
    "corsheaders",
    "rest_framework.authtoken",
    "djoser",
    "django_filters",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "crowdfunding.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.joinpath("templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crowdfunding.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


"IF YOU ARE CONFIGURING THIS APP USING WINDOWS UNCOMMENT THE FOLLOWING LINE CODE"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "crowdfunding",
        "USER": "root",
<<<<<<< HEAD
        "PASSWORD": "1234",
=======
        "PASSWORD": "",
>>>>>>> 819923e4d01a736f6f7e9b27203c569a137d1809
        "HOST": "localhost",
        "PORT": 3306,
    }
}

"IF YOU ARE CONFIGURING THIS APP USING LINUX UNCOMMENT THE FOLLOWING LINE CODE"

# DATABASES = {
#     'default': {
#         'ENGINE': 'mysql.connector.django',
#         'NAME': 'crowdfunding',
#         'USER': 'nagy',
#         'PASSWORD': 'nagy',
#         'HOST': 'localhost',
#         'PORT': 3306

#     } 
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "api.User"

import os

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:80",
    "http://localhost",
]


DJOSER = {
    "USER_MODEL": "users.Users",
    "LOGIN_FIELD": "email",
    "ACTIVATION_URL": "auth/users/activation/{uid}/{token}",
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRM_EMAIL": False,
    "PASSWORD_RESET_CONFIRM_URL": "reset-password-confirm/{uid}/{token}/",
    "LOGIN_REDIRECT_URL": "/",
    "LOGOUT_REDIRECT_URL": "/",
    "SERIALIZERS": {
        "user": "api.modelserializers.UserSerializer",
    },
}

# Authentication settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "amr.abdullah.elrefaey@gmail.com"
EMAIL_HOST_PASSWORD = "tlcq qebd rstp elpz"
DEFAULT_FROM_EMAIL = "amr.abdullah.elrefaey@gmail.comm"


SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    }
}

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24
