# Generated by Django 5.0.4 on 2024-04-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0002_alter_donation_user'),
        ('api', '0010_alter_project_tages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.project'),
        ),
    ]
