# Generated by Django 5.0.4 on 2024-05-07 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation', '0003_alter_donation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
