# Generated by Django 5.0.4 on 2024-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
