# Generated by Django 5.0.4 on 2024-04-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='images/project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='api.project')),
            ],
        ),
    ]
