# Generated by Django 5.0.4 on 2024-04-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Pics', '0002_rename_image_path_projectpics_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpics',
            old_name='image',
            new_name='image_path',
        ),
    ]
